image: node:latest

stages:
  - install
  - test

install:
  stage: install
  script:
    - npm ci

test:
  stage: test
  script:
    - npm ci
    - npm run test

lint:
  stage: test
  script:
    - npm ci
    - npm run lint
