image: node:latest

stages:
  - install
  - test

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - install
  script:
    - npm run test

lint:
  stage: test
  dependencies:
    - install
  script:
    - npm run lint
