image: node:latest

stages:
  - install
  - test

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install --legacy-peer-deps

test:
  stage: test
  dependencies:
    - install
  script:
    - npm run test

lint:
  stage: test
  dependencies:
    - install
  script:
    - npm run format
    - npm run lint